"""add socials model

Revision ID: 6b78e0936278
Revises: c8427aa69b03
Create Date: 2022-10-26 00:15:26.730326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b78e0936278'
down_revision = 'c8427aa69b03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icon')
    )
    op.create_index(op.f('ix_social_networks_id'), 'social_networks', ['id'], unique=False)
    op.create_index(op.f('ix_social_networks_link'), 'social_networks', ['link'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_networks_link'), table_name='social_networks')
    op.drop_index(op.f('ix_social_networks_id'), table_name='social_networks')
    op.drop_table('social_networks')
    # ### end Alembic commands ###
